filter items in the list
the-collab-lab/tcl-48-smart-shopping-list pull request #21
Opened 2022-10-16 19:19 UTC by snowsneakers

## Description

This code adds the ability for the user to filter the item list. We used the useState hook to store the user input and the data is filtered if it includes the input text. If the input length  > 0, a button that clear the input appears. If clicked, the input is cleared and the list become unfiltered.

## Related Issue

Closes #6 

## Acceptance Criteria

- [x] A form is added to the top of the `List` view, above the shopping list
- [x] The form includes the following elements
	- A text field (with semantic `<label>`!) which narrows down the list as the user types
	- When there’s text in the field, some kind of button (e.g., an X) to clear the field. When the field is cleared, the list is reset to its unfiltered state.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![list-before](https://user-images.githubusercontent.com/96706605/196053724-476c7bb7-fffa-4aa1-aa57-dc5f4c97fa94.png)

### After

![list-after](https://user-images.githubusercontent.com/96706605/196053729-01e17946-c795-4073-a0a0-8ee75cfa874c.png)

## Testing Steps / QA Criteria

1. Select list from nav bar
2. Enter an item into the filter item input
3. List items should be filtered by what user entered
4. Click clear button to clear input and unfilter list

2022-10-16 23:23 UTC, kaitlinLewis approved these changes
Nice work!

2022-10-17 12:46 UTC, NuriyaAkh commented
Woo hoo! Great work!

2022-10-17 12:47 UTC, NuriyaAkh approved these changes

2022-10-18 02:59 UTC, cafloyd requested changes
Nice work!! The filter seems to work as expected and will match any string against the shopping list, regardless of where that string falls in the words. The 'clear' button seems to work using keyboard navigation, which is great!

One small change request for code cleanliness, but otherwise looks awesome!
<img src="https://media4.giphy.com/media/PRo8YqHV0CjXkCqVV5/giphy.gif"/>

2022-10-18 02:59 UTC, cafloyd commented on src/views/List.jsx
> +			{/* <div> */}
Please be sure to remove this unneeded comment as well as the closing tag on line 28!

2022-10-18 22:11 UTC, cafloyd approved these changes
🎉

2022-10-18 22:31 UTC, georgeoffley approved these changes
The logic looks good! I would just make the adjustment @cafloyd suggested, and you're golden.

<img src="https://media1.giphy.com/media/4PSEQpvV5wUpnmpP1l/giphy.gif"/>

2022-10-18 23:05 UTC, daredtech approved these changes

2022-10-19 03:42 UTC, merged