Added smart feature for predicting next purchase Date
the-collab-lab/tcl-48-smart-shopping-list pull request #28
Opened 2022-11-05 16:28 UTC by meera-ramesh19

## Description

This code ensures that the suggested date for the next purchase of an item is updated to reflect how often the user actually buys the item. When an item is first added, the user makes a choice of frequency (7, 14, or 21 days) but may end up purchasing at a different interval. To be able to do this, we leveraged the function calculateEstimate from @the-collab-lab/shopping-list-utils which takes in the number of purchases (less than 2 and it is a default value of the original choice the user made), the previous estimated interval, and the number of days since the last purchase. For the previous estimate, if the item had been purchased before, we calculated the difference between the last purchased date and the next purchased date. If it had never been purchased before, we used the date created and the next purchase date. For the days since last purchase, if there was a previous purchase, we used the difference between the last purchase and current purchase date. If there was not a previous purchase, we used the difference between the date created and the current purchase date.

## Related Issue
closes #10

## Acceptance Criteria

- A getDaysBetweenDates function is exported from utils/dates.js and imported into api/firebase.js
-  This function takes two JavaScript Dates and return the number of days that have passed between them
-  When the user purchases an item, the item’s dateNextPurchased property is calculated using the calculateEstimate function and saved to the Firestore database
- -  dateNextPurchased is saved as a date, not a number

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before
DateNextPurchased always use user input value

### After
DateNextPurchased now reflects actual frequency of purchases

## Testing Steps / QA Criteria
Add new Item to the list In firestore : totalPurchase to be greater than 2, dateCreated to be date in the past. Set a dateLastPurchased ,check the item on the list to watch the dateNextPurchased changed.
to check for items with less than 2 purchases: Add new Item to the list , check item , in firestore dateNextPurchased should reflect choice when item added(ex: soon=7 days in the future, kind of soon= 14 days in the future ,notsoon=30 days in the future.

2022-11-05 16:36 UTC, snowsneakers commented
When I add an item the dateNextPurchased it correct, but when I check it, it gets set to today

2022-11-05 20:13 UTC, NuriyaAkh commented
When the item is created it assumes the correct dateNextPurchase( based on selection soon, not soon, kind of soon), but when I check the item the dateNextPurchased sets the current date

2022-11-05 20:14 UTC, NuriyaAkh requested changes
When the item is created it assumes the correct dateNextPurchase( based on selection soon, not soon, kind of soon), but when I check the item the dateNextPurchased sets the current date

2022-11-09 01:13 UTC, daredtech approved these changes
No errors! And dateNextPurchased gets updated.

2022-11-09 01:13 UTC, daredtech commented on src/api/firebase.js
> +	//console.log('add Item:', itemData.dateCreated);
The comment could be removed

2022-11-09 02:54 UTC, kaitlinLewis commented on src/api/firebase.js
> +	//console.log('add Item:', itemData.dateCreated);
Removed!

2022-11-09 22:41 UTC, NuriyaAkh approved these changes
Yahoo, it works! 
<img src="https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif"/>

2022-11-10 21:42 UTC, cafloyd approved these changes
This was such a tough issue, I'm so impressed with y'all for sticking with it and getting it over the finish line 🤩 

<img src="https://media2.giphy.com/media/prxEXMtTqRN7O/giphy.gif"/>

2022-11-10 21:51 UTC, snowsneakers approved these changes
<img src="https://media1.giphy.com/media/lYpOXbTyaTF60/giphy.gif"/>

2022-11-10 22:38 UTC, georgeoffley approved these changes
Good work finishing this up!
<img src="https://media3.giphy.com/media/J0IFnuXpYQIcnWD5v1/giphy.gif"/>

2022-11-10 23:55 UTC, merged